import Image from "next/image";
import { deleteMedia, uploadMedia } from "@/app/admin/(protected)/actions";
import { ConfirmDeleteButton, CopyMediaUrl } from "@/components/admin/media-actions";
import { AdminPageHeader, EmptyState } from "@/components/admin/ui";
import { getMediaAssets } from "@/lib/admin/data";

export const metadata={title:"Media"};
const size=(bytes:number)=>bytes<1024*1024?`${Math.round(bytes/1024)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
export default async function MediaPage(){const assets=await getMediaAssets();return <main className="admin-page"><AdminPageHeader eyebrow="Content / Library" title="Media" description="Upload and reuse approved imagery across projects, services, and website content."/>
  <section className="admin-form-section" style={{marginBottom:"1rem"}}><header className="admin-form-section__heading"><h2>Upload image</h2><p>JPG, PNG, WebP, or AVIF · maximum 8 MB.</p></header><form action={uploadMedia} className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="media-file">Image file</label><input id="media-file" name="file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" required/></div><div className="admin-field"><label htmlFor="media-alt">Alt text</label><input id="media-alt" name="alt" maxLength={300} placeholder="Describe the image for accessibility"/></div><div><button className="admin-button admin-button--primary" type="submit">Upload image</button></div></form></section>
  <section className="admin-panel">{assets.length?<div className="admin-panel__body admin-media-grid">{assets.map((asset)=><article className="admin-media-card" key={asset.id}><div className="admin-media-card__preview"><Image src={asset.public_url} alt={asset.alt_text || ""} fill sizes="(max-width: 560px) 100vw, (max-width: 820px) 50vw, 22vw"/></div><div className="admin-media-card__copy"><strong title={asset.file_name}>{asset.file_name}</strong><small>{size(Number(asset.size_bytes))}{asset.width&&asset.height?` · ${asset.width}×${asset.height}`:""}</small></div><div className="admin-media-card__actions"><CopyMediaUrl url={asset.public_url}/><form action={deleteMedia}><input type="hidden" name="id" value={asset.id}/><input type="hidden" name="path" value={asset.storage_path}/><ConfirmDeleteButton/></form></div></article>)}</div>:<EmptyState title="Media library is empty" copy="Upload the first approved project image above."/>}</section></main>}
