import Image from "next/image";
import { deleteMedia } from "@/app/admin/(protected)/actions";
import { ConfirmDeleteButton, CopyMediaUrl, MediaPreviewButton } from "@/components/admin/media-actions";
import { MediaUploadForm } from "@/components/admin/media-upload-form";
import { AdminPageHeader, EmptyState } from "@/components/admin/ui";
import { getMediaAssets, getMediaUsage } from "@/lib/admin/data";

export const metadata={title:"Media"};
const size=(bytes:number)=>bytes<1024*1024?`${Math.round(bytes/1024)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
export default async function MediaPage({searchParams}:{searchParams:Promise<{query?:string;type?:string}>}){const params=await searchParams;const assets=await getMediaAssets(params);const usage=await getMediaUsage(assets);return <main className="admin-page"><AdminPageHeader eyebrow="Content / Library" title="Media" description="Upload, search, preview, and safely reuse approved website imagery."/>
  <div style={{marginBottom:"1rem"}}><MediaUploadForm/></div><form className="admin-toolbar"><div className="admin-field"><label htmlFor="media-query">Search media</label><input id="media-query" name="query" defaultValue={params.query} placeholder="Filename or alt text"/></div><div className="admin-field"><label htmlFor="media-type">File type</label><select id="media-type" name="type" defaultValue={params.type||""}><option value="">All images</option><option value="jpeg">JPEG</option><option value="png">PNG</option><option value="webp">WebP</option><option value="avif">AVIF</option></select></div><button className="admin-button">Filter</button></form>
  <section className="admin-panel">{assets.length?<div className="admin-panel__body admin-media-grid">{assets.map((asset)=><article className="admin-media-card" key={asset.id}><div className="admin-media-card__preview"><Image src={asset.public_url} alt={asset.alt_text || ""} fill sizes="(max-width: 560px) 100vw, (max-width: 820px) 50vw, 22vw"/><MediaPreviewButton url={asset.public_url} alt={asset.alt_text||""} fileName={asset.file_name}/>{usage[asset.id]>0&&<span className="admin-media-card__used">Used {usage[asset.id]}×</span>}</div><div className="admin-media-card__copy"><strong title={asset.file_name}>{asset.file_name}</strong><small>{size(Number(asset.size_bytes))}{asset.width&&asset.height?` · ${asset.width}×${asset.height}`:""}</small><small>{new Date(asset.created_at).toLocaleDateString()} · {asset.alt_text||"No alt text"}</small></div><div className="admin-media-card__actions"><CopyMediaUrl url={asset.public_url}/><form action={deleteMedia}><input type="hidden" name="id" value={asset.id}/><input type="hidden" name="path" value={asset.storage_path}/><ConfirmDeleteButton disabled={usage[asset.id]>0} message={usage[asset.id]>0?"This image is referenced and cannot be deleted.":"Delete this unused image permanently?"}/></form></div></article>)}</div>:<EmptyState title="No media found" copy={params.query?"Try a different search or file type.":"Upload the first approved website image above."}/>}</section></main>}
