"use client";

import Link from "next/link";
import { useActionState, useEffect, useState } from "react";
import { saveHomepageContent, type CmsActionState } from "@/app/admin/(protected)/actions";
import { MediaPicker, type MediaOption } from "@/components/admin/media-picker";
import type { HomepageContent } from "@/lib/content/homepage";

interface SelectableRecord { id: string; title: string; slug: string; featured: boolean; sort_order: number; status?: string; active?: boolean }
interface HomepageEditorProps { initial: HomepageContent; assets: MediaOption[]; projects: SelectableRecord[]; services: SelectableRecord[]; updatedAt: string | null }

const initialState: CmsActionState = { status: "idle", message: "" };

function Count({ value, max }: { value: string; max: number }) { return <span className={value.length > max * .9 ? "admin-count admin-count--near" : "admin-count"}>{value.length}/{max}</span>; }
function Toggle({ name, checked, onChange, label }: { name: string; checked: boolean; onChange: (checked:boolean)=>void; label: string }) { return <label className="admin-switch"><input name={name} type="checkbox" checked={checked} onChange={(event)=>onChange(event.target.checked)}/><span aria-hidden="true"/><strong>{label}</strong></label>; }

function OrderedSelection({ name, records, selected, setSelected, limit }: { name:string;records:SelectableRecord[];selected:string[];setSelected:(items:string[])=>void;limit:number }) {
  const selectedRecords=selected.map((id)=>records.find((item)=>item.id===id)).filter(Boolean) as SelectableRecord[];
  return <div className="admin-selection-manager">
    <div className="admin-selection-manager__available">{records.map((record)=><label key={record.id}><input type="checkbox" checked={selected.includes(record.id)} onChange={(event)=>{if(event.target.checked){if(selected.length>=limit){window.alert(`Choose no more than ${limit}.`);return;}setSelected([...selected,record.id]);}else setSelected(selected.filter((id)=>id!==record.id));}}/><span><strong>{record.title}</strong><small>/{record.slug}</small></span></label>)}</div>
    {selectedRecords.length>0&&<ol className="admin-selection-manager__order">{selectedRecords.map((record,index)=><li key={record.id}><input type="hidden" name={name} value={record.id}/><span>{String(index+1).padStart(2,"0")}</span><strong>{record.title}</strong><div><button type="button" disabled={index===0} onClick={()=>{const next=[...selected];[next[index-1],next[index]]=[next[index],next[index-1]];setSelected(next);}} aria-label={`Move ${record.title} up`}>↑</button><button type="button" disabled={index===selected.length-1} onClick={()=>{const next=[...selected];[next[index+1],next[index]]=[next[index],next[index+1]];setSelected(next);}} aria-label={`Move ${record.title} down`}>↓</button></div></li>)}</ol>}
    <small>{selected.length}/{limit} selected. Use arrows to control homepage order.</small>
  </div>;
}

export function HomepageEditor({ initial, assets, projects, services, updatedAt }: HomepageEditorProps) {
  const [state, action, pending] = useActionState(saveHomepageContent, initialState);
  const [draft,setDraft]=useState(initial);
  const [dirty,setDirty]=useState(false);
  const [tab,setTab]=useState<"editor"|"preview">("editor");
  const [device,setDevice]=useState<"desktop"|"mobile">("desktop");
  const [stats,setStats]=useState(initial.stats.items);
  const [selectedProjects,setSelectedProjects]=useState(projects.filter((item)=>item.featured).sort((a,b)=>a.sort_order-b.sort_order).map((item)=>item.id));
  const [selectedServices,setSelectedServices]=useState(services.filter((item)=>item.featured).sort((a,b)=>a.sort_order-b.sort_order).map((item)=>item.id));
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(!dirty)return;event.preventDefault();event.returnValue="";};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  const update=<K extends keyof HomepageContent>(section:K,value:HomepageContent[K])=>{setDraft((current)=>({...current,[section]:value}));setDirty(true);};
  return <>
    <div className="admin-editor-tabs"><button type="button" data-active={tab==="editor"} onClick={()=>setTab("editor")}>Editor</button><button type="button" data-active={tab==="preview"} onClick={()=>setTab("preview")}>Preview</button><Link href="/" target="_blank">Open live page ↗</Link></div>
    {state.message&&<div className={`admin-toast admin-toast--${state.status}`} role="status">{state.message}</div>}
    {tab==="preview"&&<section className="admin-preview-panel"><header><div><strong>Hero preview</strong><small>Content and approved layout only; the live site retains its full design system.</small></div><div><button type="button" data-active={device==="desktop"} onClick={()=>setDevice("desktop")}>Desktop</button><button type="button" data-active={device==="mobile"} onClick={()=>setDevice("mobile")}>Mobile</button></div></header><div className={`admin-hero-preview admin-hero-preview--${device} admin-hero-preview--${draft.hero.alignment}`} style={draft.hero.image?{backgroundImage:`linear-gradient(rgb(0 0 0 / ${draft.hero.overlay}%),rgb(0 0 0 / ${draft.hero.overlay}%)),url(${draft.hero.image.url})`}:{}}><div><span>{draft.hero.eyebrow}</span><h2>{draft.hero.heading}</h2><p>{draft.hero.description}</p><div><b>{draft.hero.primaryCtaText} ↗</b>{draft.hero.secondaryCtaEnabled&&<b>{draft.hero.secondaryCtaText} ↗</b>}</div></div></div></section>}
    <form action={(formData)=>{setDirty(false);action(formData);}} className={`admin-form-sections${tab==="preview"?" admin-editor-hidden":""}`} onChange={()=>setDirty(true)}>
      <details className="admin-form-section" open><summary className="admin-form-section__heading"><div><h2>Hero</h2><p>Primary first impression with guarded layouts and contrast.</p></div><span>Required</span></summary><div className="admin-form-section__body admin-form-grid">
        <div className="admin-field"><label className="admin-field__label" htmlFor="hero-eyebrow">Eyebrow <Count value={draft.hero.eyebrow} max={60}/></label><input id="hero-eyebrow" name="heroEyebrow" value={draft.hero.eyebrow} onChange={(e)=>update("hero",{...draft.hero,eyebrow:e.target.value})} maxLength={60}/></div>
        <div className="admin-field"><label htmlFor="hero-layout">Layout preset</label><select id="hero-layout" name="heroLayout" value={draft.hero.layout} onChange={(e)=>update("hero",{...draft.hero,layout:e.target.value as typeof draft.hero.layout})}><option value="standard">Standard</option><option value="split">Split</option><option value="minimal">Minimal</option></select></div>
        <div className="admin-field admin-field--wide"><label className="admin-field__label" htmlFor="hero-heading">Main heading <Count value={draft.hero.heading} max={90}/></label><input id="hero-heading" name="heroHeading" required value={draft.hero.heading} onChange={(e)=>update("hero",{...draft.hero,heading:e.target.value})} maxLength={90}/></div>
        <div className="admin-field admin-field--wide"><label className="admin-field__label" htmlFor="hero-description">Supporting paragraph <Count value={draft.hero.description} max={240}/></label><textarea id="hero-description" name="heroDescription" required value={draft.hero.description} onChange={(e)=>update("hero",{...draft.hero,description:e.target.value})} maxLength={240}/></div>
        <div className="admin-field"><label htmlFor="hero-primary-text">Primary CTA</label><input id="hero-primary-text" name="heroPrimaryText" required value={draft.hero.primaryCtaText} onChange={(e)=>update("hero",{...draft.hero,primaryCtaText:e.target.value})} maxLength={36}/></div><div className="admin-field"><label htmlFor="hero-primary-url">Primary CTA URL</label><input id="hero-primary-url" name="heroPrimaryUrl" required value={draft.hero.primaryCtaUrl} onChange={(e)=>update("hero",{...draft.hero,primaryCtaUrl:e.target.value})} maxLength={2000}/></div>
        <div className="admin-field"><label htmlFor="hero-secondary-text">Secondary CTA</label><input id="hero-secondary-text" name="heroSecondaryText" value={draft.hero.secondaryCtaText} onChange={(e)=>update("hero",{...draft.hero,secondaryCtaText:e.target.value})} maxLength={36}/></div><div className="admin-field"><label htmlFor="hero-secondary-url">Secondary CTA URL</label><input id="hero-secondary-url" name="heroSecondaryUrl" value={draft.hero.secondaryCtaUrl} onChange={(e)=>update("hero",{...draft.hero,secondaryCtaUrl:e.target.value})} maxLength={2000}/></div>
        <Toggle name="heroSecondaryEnabled" checked={draft.hero.secondaryCtaEnabled} onChange={(checked)=>update("hero",{...draft.hero,secondaryCtaEnabled:checked})} label="Show secondary CTA"/>
        <div className="admin-field"><label htmlFor="hero-alignment">Text alignment</label><select id="hero-alignment" name="heroAlignment" value={draft.hero.alignment} onChange={(e)=>update("hero",{...draft.hero,alignment:e.target.value as "left"|"center"})}><option value="left">Left</option><option value="center">Center</option></select></div>
        <div className="admin-field admin-field--wide"><label className="admin-field__label" htmlFor="hero-overlay">Overlay intensity <span>{draft.hero.overlay}%</span></label><input id="hero-overlay" name="heroOverlay" type="range" min={10} max={80} value={draft.hero.overlay} onChange={(e)=>update("hero",{...draft.hero,overlay:Number(e.target.value)})}/></div>
        <div className="admin-field--wide admin-media-pair"><MediaPicker name="heroImage" label="Desktop hero image" value={draft.hero.image} assets={assets} requiredAlt/><MediaPicker name="heroMobileImage" label="Optional mobile hero image" value={draft.hero.mobileImage} assets={assets}/></div>
      </div></details>

      <details className="admin-form-section" open><summary className="admin-form-section__heading"><div><h2>About</h2><p>Company introduction with an optional supporting image.</p></div><Toggle name="aboutVisible" checked={draft.about.visible} onChange={(checked)=>update("about",{...draft.about,visible:checked})} label={draft.about.visible?"Visible":"Hidden"}/></summary><div className="admin-form-section__body admin-form-grid">
        <div className="admin-field"><label htmlFor="about-label">Section label</label><input id="about-label" name="aboutLabel" value={draft.about.label} onChange={(e)=>update("about",{...draft.about,label:e.target.value})} maxLength={60}/></div><div className="admin-field"><label htmlFor="about-heading">Heading</label><input id="about-heading" name="aboutHeading" value={draft.about.heading} onChange={(e)=>update("about",{...draft.about,heading:e.target.value})} maxLength={140}/></div>
        <div className="admin-field admin-field--wide"><label className="admin-field__label" htmlFor="about-description">Description <Count value={draft.about.description} max={700}/></label><textarea id="about-description" name="aboutDescription" value={draft.about.description} onChange={(e)=>update("about",{...draft.about,description:e.target.value})} maxLength={700}/></div><div className="admin-field admin-field--wide"><label htmlFor="about-secondary">Secondary paragraph</label><textarea id="about-secondary" name="aboutSecondaryDescription" value={draft.about.secondaryDescription} onChange={(e)=>update("about",{...draft.about,secondaryDescription:e.target.value})} maxLength={500}/></div>
        <div className="admin-field"><label htmlFor="about-cta">CTA label</label><input id="about-cta" name="aboutCtaText" value={draft.about.ctaText} onChange={(e)=>update("about",{...draft.about,ctaText:e.target.value})} maxLength={36}/></div><div className="admin-field"><label htmlFor="about-url">CTA URL</label><input id="about-url" name="aboutCtaUrl" value={draft.about.ctaUrl} onChange={(e)=>update("about",{...draft.about,ctaUrl:e.target.value})}/></div>
        <div className="admin-field--wide admin-media-pair"><MediaPicker name="aboutImage" label="Main image" value={draft.about.image} assets={assets}/><MediaPicker name="aboutSecondaryImage" label="Secondary image" value={draft.about.secondaryImage} assets={assets}/></div>
      </div></details>

      <details className="admin-form-section" open><summary className="admin-form-section__heading"><div><h2>Company statistics</h2><p>Up to six concise proof points. Four is ideal.</p></div><Toggle name="statsVisible" checked={draft.stats.visible} onChange={(checked)=>update("stats",{...draft.stats,visible:checked})} label={draft.stats.visible?"Visible":"Hidden"}/></summary><div className="admin-form-section__body"><div className="admin-repeater">{stats.map((stat,index)=><div className="admin-repeater__row" key={index}><span>{String(index+1).padStart(2,"0")}</span><div className="admin-field"><label>Value</label><input name="statValue" value={stat.value} maxLength={16} onChange={(e)=>{const next=[...stats];next[index]={...stat,value:e.target.value};setStats(next);setDirty(true);}} required/></div><div className="admin-field"><label>Label</label><input name="statLabel" value={stat.label} maxLength={60} onChange={(e)=>{const next=[...stats];next[index]={...stat,label:e.target.value};setStats(next);setDirty(true);}} required/></div><div><button type="button" disabled={index===0} onClick={()=>{const next=[...stats];[next[index-1],next[index]]=[next[index],next[index-1]];setStats(next);}}>↑</button><button type="button" disabled={index===stats.length-1} onClick={()=>{const next=[...stats];[next[index+1],next[index]]=[next[index],next[index+1]];setStats(next);}}>↓</button><button type="button" disabled={stats.length===1} onClick={()=>setStats(stats.filter((_,itemIndex)=>itemIndex!==index))}>×</button></div></div>)}</div>{stats.length<6&&<button className="admin-button" type="button" onClick={()=>setStats([...stats,{value:"",label:""}])}>+ Add statistic</button>}</div></details>

      <details className="admin-form-section"><summary className="admin-form-section__heading"><div><h2>Services</h2><p>Select existing services; full service content stays in its own editor.</p></div><Toggle name="servicesVisible" checked={draft.services.visible} onChange={(checked)=>update("services",{...draft.services,visible:checked})} label={draft.services.visible?"Visible":"Hidden"}/></summary><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="services-eyebrow">Section label</label><input id="services-eyebrow" name="servicesEyebrow" value={draft.services.eyebrow} onChange={(e)=>update("services",{...draft.services,eyebrow:e.target.value})} maxLength={60}/></div><div className="admin-field"><label htmlFor="services-heading">Heading</label><input id="services-heading" name="servicesHeading" value={draft.services.heading} onChange={(e)=>update("services",{...draft.services,heading:e.target.value})} maxLength={80}/></div><div className="admin-field"><label htmlFor="services-layout">Display preset</label><select id="services-layout" name="servicesLayout" value={draft.services.layout} onChange={(e)=>update("services",{...draft.services,layout:e.target.value as "list"|"cards"})}><option value="list">Editorial list</option><option value="cards">Cards</option></select></div><div className="admin-field"><label htmlFor="services-subheading">Subheading</label><input id="services-subheading" name="servicesSubheading" value={draft.services.subheading} onChange={(e)=>update("services",{...draft.services,subheading:e.target.value})} maxLength={180}/></div><div className="admin-field--wide"><OrderedSelection name="featuredServices" records={services} selected={selectedServices} setSelected={(items)=>{setSelectedServices(items);setDirty(true);}} limit={6}/></div></div></details>

      <details className="admin-form-section"><summary className="admin-form-section__heading"><div><h2>Featured projects</h2><p>Select and order published portfolio entries.</p></div><Toggle name="projectsVisible" checked={draft.projects.visible} onChange={(checked)=>update("projects",{...draft.projects,visible:checked})} label={draft.projects.visible?"Visible":"Hidden"}/></summary><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="projects-eyebrow">Section label</label><input id="projects-eyebrow" name="projectsEyebrow" value={draft.projects.eyebrow} onChange={(e)=>update("projects",{...draft.projects,eyebrow:e.target.value})} maxLength={60}/></div><div className="admin-field"><label htmlFor="projects-heading">Heading</label><input id="projects-heading" name="projectsHeading" value={draft.projects.heading} onChange={(e)=>update("projects",{...draft.projects,heading:e.target.value})} maxLength={80}/></div><div className="admin-field"><label htmlFor="projects-layout">Display preset</label><select id="projects-layout" name="projectsLayout" value={draft.projects.layout} onChange={(e)=>update("projects",{...draft.projects,layout:e.target.value as "editorial"|"grid"})}><option value="editorial">Editorial</option><option value="grid">Balanced grid</option></select></div><div className="admin-field"><label htmlFor="projects-subheading">Subheading</label><input id="projects-subheading" name="projectsSubheading" value={draft.projects.subheading} onChange={(e)=>update("projects",{...draft.projects,subheading:e.target.value})} maxLength={180}/></div><div className="admin-field--wide"><OrderedSelection name="featuredProjects" records={projects.filter((item)=>item.status==="published")} selected={selectedProjects} setSelected={(items)=>{setSelectedProjects(items);setDirty(true);}} limit={5}/></div></div></details>

      <details className="admin-form-section"><summary className="admin-form-section__heading"><div><h2>Testimonials</h2><p>Visibility and section copy. Manage client records separately.</p></div><Toggle name="testimonialsVisible" checked={draft.testimonials.visible} onChange={(checked)=>update("testimonials",{...draft.testimonials,visible:checked})} label={draft.testimonials.visible?"Visible":"Hidden"}/></summary><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="testimonials-eyebrow">Section label</label><input id="testimonials-eyebrow" name="testimonialsEyebrow" value={draft.testimonials.eyebrow} onChange={(e)=>update("testimonials",{...draft.testimonials,eyebrow:e.target.value})} maxLength={60}/></div><div className="admin-field"><label htmlFor="testimonials-heading">Heading</label><input id="testimonials-heading" name="testimonialsHeading" value={draft.testimonials.heading} onChange={(e)=>update("testimonials",{...draft.testimonials,heading:e.target.value})} maxLength={100}/></div><div><Link className="admin-button" href="/admin/content/testimonials">Manage testimonials</Link></div></div></details>

      <details className="admin-form-section"><summary className="admin-form-section__heading"><div><h2>Final CTA</h2><p>A focused closing invitation with optional imagery.</p></div><Toggle name="ctaVisible" checked={draft.cta.visible} onChange={(checked)=>update("cta",{...draft.cta,visible:checked})} label={draft.cta.visible?"Visible":"Hidden"}/></summary><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="cta-eyebrow">Eyebrow</label><input id="cta-eyebrow" name="ctaEyebrow" value={draft.cta.eyebrow} onChange={(e)=>update("cta",{...draft.cta,eyebrow:e.target.value})} maxLength={60}/></div><div className="admin-field"><label htmlFor="cta-heading">Heading</label><input id="cta-heading" name="ctaHeading" value={draft.cta.heading} onChange={(e)=>update("cta",{...draft.cta,heading:e.target.value})} maxLength={110}/></div><div className="admin-field admin-field--wide"><label htmlFor="cta-description">Description</label><textarea id="cta-description" name="ctaDescription" value={draft.cta.description} onChange={(e)=>update("cta",{...draft.cta,description:e.target.value})} maxLength={240}/></div><div className="admin-field"><label htmlFor="cta-button">Button label</label><input id="cta-button" name="ctaButtonText" value={draft.cta.buttonText} onChange={(e)=>update("cta",{...draft.cta,buttonText:e.target.value})} maxLength={36}/></div><div className="admin-field"><label htmlFor="cta-url">Button URL</label><input id="cta-url" name="ctaButtonUrl" value={draft.cta.buttonUrl} onChange={(e)=>update("cta",{...draft.cta,buttonUrl:e.target.value})}/></div><div className="admin-field--wide"><MediaPicker name="ctaImage" label="Background image" value={draft.cta.image} assets={assets}/></div></div></details>

      <details className="admin-form-section"><summary className="admin-form-section__heading"><div><h2>Homepage SEO</h2><p>Search and social preview defaults for the homepage.</p></div><span>SEO</span></summary><div className="admin-form-section__body admin-form-grid"><div className="admin-field admin-field--wide"><label className="admin-field__label" htmlFor="seo-title">SEO title <Count value={draft.seo.title} max={70}/></label><input id="seo-title" name="seoTitle" value={draft.seo.title} onChange={(e)=>update("seo",{...draft.seo,title:e.target.value})} maxLength={70}/></div><div className="admin-field admin-field--wide"><label className="admin-field__label" htmlFor="seo-description">Meta description <Count value={draft.seo.description} max={180}/></label><textarea id="seo-description" name="seoDescription" value={draft.seo.description} onChange={(e)=>update("seo",{...draft.seo,description:e.target.value})} maxLength={180}/></div><div className="admin-field"><label htmlFor="seo-canonical">Canonical URL</label><input id="seo-canonical" name="seoCanonical" value={draft.seo.canonical} onChange={(e)=>update("seo",{...draft.seo,canonical:e.target.value})}/></div><div className="admin-field--wide"><MediaPicker name="seoImage" label="Open Graph image" value={draft.seo.ogImage} assets={assets}/></div></div></details>

      <footer className="admin-form-footer admin-publish-bar"><div><strong>{dirty?"Unsaved changes":"All changes saved"}</strong><small>{updatedAt?`Last updated ${new Date(updatedAt).toLocaleString()}`:"Not published yet"}</small></div><button className="admin-button admin-button--primary" type="submit" disabled={pending}>{pending?"Publishing…":"Save & publish"}</button></footer>
    </form>
  </>;
}
