"use client";

import Image from "next/image";
import { useRef, useState } from "react";
import { useFormStatus } from "react-dom";
import { uploadMedia } from "@/app/admin/(protected)/actions";

function UploadButton(){const{pending}=useFormStatus();return <button className="admin-button admin-button--primary" disabled={pending}>{pending?"Uploading…":"Upload image"}</button>}

export function MediaUploadForm(){const inputRef=useRef<HTMLInputElement>(null);const[preview,setPreview]=useState("");const[error,setError]=useState("");const[dimensions,setDimensions]=useState({width:0,height:0});const[dragging,setDragging]=useState(false);
  function inspect(file?:File){setError("");if(!file)return;if(!["image/jpeg","image/png","image/webp","image/avif"].includes(file.type)||file.size>8*1024*1024){setError("Use a JPG, PNG, WebP, or AVIF image up to 8 MB.");if(inputRef.current)inputRef.current.value="";return;}const url=URL.createObjectURL(file);setPreview((old)=>{if(old.startsWith("blob:"))URL.revokeObjectURL(old);return url;});const image=new window.Image();image.onload=()=>setDimensions({width:image.naturalWidth,height:image.naturalHeight});image.src=url;}
  return <form action={uploadMedia} className="admin-form-section"><header className="admin-form-section__heading"><h2>Upload image</h2><p>Files are stored in Supabase Storage, never in the source repository.</p></header><div className="admin-form-section__body admin-form-grid"><input type="hidden" name="width" value={dimensions.width||""}/><input type="hidden" name="height" value={dimensions.height||""}/><label className={`admin-dropzone admin-field--wide${dragging?" admin-dropzone--active":""}`} onDragEnter={()=>setDragging(true)} onDragLeave={()=>setDragging(false)} onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{event.preventDefault();setDragging(false);const file=event.dataTransfer.files[0];if(!file||!inputRef.current)return;const transfer=new DataTransfer();transfer.items.add(file);inputRef.current.files=transfer.files;inspect(file);}}>{preview?<Image src={preview} alt="Upload preview" fill unoptimized sizes="60vw"/>:<span><strong>Drag & drop an image</strong><small>or click to browse · maximum 8 MB</small></span>}<input ref={inputRef} name="file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" required onChange={(event)=>inspect(event.target.files?.[0])}/></label>{error&&<p className="admin-form-error admin-field--wide" role="alert">{error}</p>}<div className="admin-field"><label htmlFor="media-folder">Collection</label><select id="media-folder" name="folder" defaultValue="site/homepage"><option value="site/homepage">Homepage</option><option value="site/projects">Projects</option><option value="site/services">Services</option><option value="site/testimonials">Testimonials</option><option value="site/seo">SEO / social</option></select></div><div className="admin-field"><label htmlFor="media-alt">Alt text</label><input id="media-alt" name="alt" maxLength={300} placeholder="Describe the image for accessibility"/><small>{dimensions.width?`${dimensions.width} × ${dimensions.height}px`:"Dimensions are detected before upload."}</small></div><div><UploadButton/></div></div></form>}
