import Link from "next/link";
import { archiveProject, saveProject } from "@/app/admin/(protected)/actions";
import { projectCategories } from "@/types/content";
import { MediaPicker, type MediaOption } from "@/components/admin/media-picker";
import { GalleryManager } from "@/components/admin/gallery-manager";

interface ProjectRecord {
  id:string; slug:string; title:string; summary:string; description:string; story:string[]; challenge:string; approach:string; outcome:string; client_name:string|null; location:string; category:string; completion_year:number|null;
  project_size:string|null;project_value?:string|null; delivery_method:string|null; services:string[];hero_image_path?:string|null; hero_image_url:string|null; hero_image_alt:string|null;hero_image_width?:number|null;hero_image_height?:number|null; metrics:Array<{value:string;label:string}>; seo_title:string|null; seo_description:string|null;og_image_path?:string|null;og_image_url?:string|null;canonical_url?:string|null;
  status:"draft"|"published"|"archived"; featured:boolean; sort_order:number; project_images:Array<{public_url:string;alt_text:string;storage_path?:string|null}>;
}

export function ProjectEditor({ project, assets=[] }: { project?: ProjectRecord | null;assets?:MediaOption[] }) {
  const metrics = project?.metrics?.map((metric) => `${metric.value} | ${metric.label}`).join("\n") || "";
  const hero=project?.hero_image_url?{url:project.hero_image_url,path:project.hero_image_path||"",alt:project.hero_image_alt||"",width:project.hero_image_width||null,height:project.hero_image_height||null}:null;
  const og=project?.og_image_url?{url:project.og_image_url,path:project.og_image_path||"",alt:project.hero_image_alt||"",width:1200,height:630}:null;
  return <form action={saveProject} className="admin-form-sections">{project && <input type="hidden" name="id" value={project.id}/>}<section className="admin-form-section"><header className="admin-form-section__heading"><h2>General</h2><p>The project identity shown throughout the website.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="project-title">Project title</label><input id="project-title" name="title" defaultValue={project?.title} required minLength={2} maxLength={140}/></div><div className="admin-field"><label htmlFor="project-slug">URL slug</label><input id="project-slug" name="slug" defaultValue={project?.slug} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="the-meridian"/><small>Lowercase letters, numbers, and hyphens.</small></div><div className="admin-field admin-field--wide"><label htmlFor="project-summary">Short summary</label><textarea id="project-summary" name="summary" defaultValue={project?.summary} required minLength={20} maxLength={400}/></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>Project details</h2><p>Core facts used on project listings and detail pages.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="project-client">Client</label><input id="project-client" name="clientName" defaultValue={project?.client_name || ""} maxLength={160}/></div><div className="admin-field"><label htmlFor="project-location">Location</label><input id="project-location" name="location" defaultValue={project?.location} maxLength={160}/></div><div className="admin-field"><label htmlFor="project-category">Category</label><select id="project-category" name="category" defaultValue={project?.category || "Commercial"}>{projectCategories.map((category)=><option key={category}>{category}</option>)}</select></div><div className="admin-field"><label htmlFor="project-year">Completion year</label><input id="project-year" name="completionYear" type="number" min={1900} max={2200} defaultValue={project?.completion_year || ""}/></div><div className="admin-field"><label htmlFor="project-size">Project size</label><input id="project-size" name="projectSize" defaultValue={project?.project_size || ""} maxLength={100}/></div><div className="admin-field"><label htmlFor="project-value">Project value</label><input id="project-value" name="projectValue" defaultValue={project?.project_value || ""} maxLength={100}/></div><div className="admin-field"><label htmlFor="project-delivery">Delivery method</label><input id="project-delivery" name="deliveryMethod" defaultValue={project?.delivery_method || ""} maxLength={120}/></div><div className="admin-field admin-field--wide"><label htmlFor="project-services">Services performed</label><textarea id="project-services" name="services" defaultValue={project?.services?.join("\n")}/><small>One service per line.</small></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>Content</h2><p>Build a clear project story without working in a raw CMS blob.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field admin-field--wide"><label htmlFor="project-description">Full description</label><textarea id="project-description" name="description" defaultValue={project?.description}/></div><div className="admin-field admin-field--wide"><label htmlFor="project-story">Project story</label><textarea id="project-story" name="story" defaultValue={project?.story?.join("\n")}/><small>One paragraph per line.</small></div><div className="admin-field"><label htmlFor="project-challenge">Challenge</label><textarea id="project-challenge" name="challenge" defaultValue={project?.challenge}/></div><div className="admin-field"><label htmlFor="project-approach">Approach</label><textarea id="project-approach" name="approach" defaultValue={project?.approach}/></div><div className="admin-field admin-field--wide"><label htmlFor="project-outcome">Outcome</label><textarea id="project-outcome" name="outcome" defaultValue={project?.outcome}/></div><div className="admin-field admin-field--wide"><label htmlFor="project-metrics">Project statistics</label><textarea id="project-metrics" name="metrics" defaultValue={metrics} placeholder={'420K | Square Feet\n31 | Months'}/><small>One per line in “value | label” format.</small></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>Media</h2><p>Upload to Supabase Storage or choose an approved image from the Media Library.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field--wide"><MediaPicker name="projectHero" label="Project hero image" value={hero} assets={assets} requiredAlt/></div><div className="admin-field admin-field--wide"><span className="admin-field__label">Project gallery</span><GalleryManager initial={project?.project_images||[]} assets={assets}/></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>SEO</h2><p>Optional overrides; the project title and summary are used by default.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="project-seo-title">SEO title</label><input id="project-seo-title" name="seoTitle" defaultValue={project?.seo_title || ""} maxLength={70}/></div><div className="admin-field"><label htmlFor="project-canonical">Canonical URL</label><input id="project-canonical" name="canonicalUrl" defaultValue={project?.canonical_url||""} placeholder="/projects/project-slug"/></div><div className="admin-field admin-field--wide"><label htmlFor="project-seo-description">SEO description</label><textarea id="project-seo-description" name="seoDescription" defaultValue={project?.seo_description || ""} maxLength={180}/></div><div className="admin-field--wide"><MediaPicker name="projectOg" label="Open Graph image" value={og} assets={assets}/></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>Publishing</h2><p>Drafts remain private; published projects appear on the public website.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="project-status">Status</label><select id="project-status" name="status" defaultValue={project?.status || "draft"}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div><div className="admin-field"><label htmlFor="project-order">Sort order</label><input id="project-order" name="sortOrder" type="number" defaultValue={project?.sort_order || 0}/></div><label className="admin-field"><span>Featured placement</span><span><input name="featured" type="checkbox" defaultChecked={project?.featured}/> Show in featured project areas</span></label></div></section>
    <footer className="admin-form-footer"><Link className="admin-button" href="/admin/projects">Cancel</Link><button className="admin-button admin-button--primary" type="submit">{project ? "Save changes" : "Create project"}</button></footer>
    {project && <section className="admin-form-section admin-danger-zone"><header className="admin-form-section__heading"><h2>Archive project</h2><p>Removes the project from the public website without deleting its content.</p></header><div className="admin-form-section__body"><button className="admin-button admin-button--danger" formAction={archiveProject} name="id" value={project.id}>Archive project</button></div></section>}
  </form>;
}
