import Link from "next/link";
import { saveService } from "@/app/admin/(protected)/actions";

interface ServiceRecord { id:string;slug:string;title:string;number:string;summary:string;description:string;capabilities:string[];related_project_slugs:string[];image_url:string|null;image_alt:string|null;seo_title:string|null;seo_description:string|null;active:boolean;featured:boolean;sort_order:number }

export function ServiceEditor({ service }: { service?: ServiceRecord | null }) {
  return <form action={saveService} className="admin-form-sections">{service && <input type="hidden" name="id" value={service.id}/>}<section className="admin-form-section"><header className="admin-form-section__heading"><h2>General</h2><p>Service identity and public listing copy.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="service-title">Title</label><input id="service-title" name="title" defaultValue={service?.title} required minLength={2} maxLength={140}/></div><div className="admin-field"><label htmlFor="service-slug">URL slug</label><input id="service-slug" name="slug" defaultValue={service?.slug} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></div><div className="admin-field"><label htmlFor="service-number">Display number</label><input id="service-number" name="number" defaultValue={service?.number || "01"} required maxLength={8}/></div><div className="admin-field"><label htmlFor="service-order">Sort order</label><input id="service-order" name="sortOrder" type="number" defaultValue={service?.sort_order || 0}/></div><div className="admin-field admin-field--wide"><label htmlFor="service-summary">Short summary</label><textarea id="service-summary" name="summary" defaultValue={service?.summary} required minLength={20} maxLength={400}/></div><div className="admin-field admin-field--wide"><label htmlFor="service-description">Full description</label><textarea id="service-description" name="description" defaultValue={service?.description}/></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>Capabilities & projects</h2><p>Structured lists keep the service page concise and scannable.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="service-capabilities">Capabilities</label><textarea id="service-capabilities" name="capabilities" defaultValue={service?.capabilities?.join("\n")}/><small>One capability per line.</small></div><div className="admin-field"><label htmlFor="service-projects">Related project slugs</label><textarea id="service-projects" name="relatedProjects" defaultValue={service?.related_project_slugs?.join("\n")}/><small>One project slug per line.</small></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>Media & SEO</h2><p>Use an image URL from the Media Library or approved source.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field admin-field--wide"><label htmlFor="service-image">Image URL</label><input id="service-image" name="imageUrl" type="url" defaultValue={service?.image_url || ""}/></div><div className="admin-field admin-field--wide"><label htmlFor="service-alt">Image alt text</label><input id="service-alt" name="imageAlt" defaultValue={service?.image_alt || ""} maxLength={300}/></div><div className="admin-field"><label htmlFor="service-seo-title">SEO title</label><input id="service-seo-title" name="seoTitle" defaultValue={service?.seo_title || ""} maxLength={70}/></div><div className="admin-field"><label htmlFor="service-seo-description">SEO description</label><textarea id="service-seo-description" name="seoDescription" defaultValue={service?.seo_description || ""} maxLength={180}/></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>Publishing</h2><p>Disabled services are removed from public navigation and pages.</p></header><div className="admin-form-section__body admin-form-grid"><label className="admin-field"><span>Visibility</span><span><input name="active" type="checkbox" defaultChecked={service?.active ?? true}/> Active on website</span></label><label className="admin-field"><span>Featured placement</span><span><input name="featured" type="checkbox" defaultChecked={service?.featured}/> Feature this service</span></label></div></section><footer className="admin-form-footer"><Link className="admin-button" href="/admin/services">Cancel</Link><button className="admin-button admin-button--primary" type="submit">{service ? "Save changes" : "Create service"}</button></footer></form>;
}
