import Link from "next/link";
import { saveService } from "@/app/admin/(protected)/actions";
import { MediaPicker, type MediaOption } from "@/components/admin/media-picker";

interface ServiceRecord { id:string;slug:string;title:string;number:string;summary:string;description:string;capabilities:string[];related_project_slugs:string[];image_path?:string|null;image_url:string|null;image_alt:string|null;image_width?:number|null;image_height?:number|null;icon?:string|null;seo_title:string|null;seo_description:string|null;og_image_path?:string|null;og_image_url?:string|null;canonical_url?:string|null;active:boolean;featured:boolean;sort_order:number }

export function ServiceEditor({ service,assets=[] }: { service?: ServiceRecord | null;assets?:MediaOption[] }) {
  const image=service?.image_url?{url:service.image_url,path:service.image_path||"",alt:service.image_alt||"",width:service.image_width||null,height:service.image_height||null}:null;
  const og=service?.og_image_url?{url:service.og_image_url,path:service.og_image_path||"",alt:service.image_alt||"",width:1200,height:630}:null;
  return <form action={saveService} className="admin-form-sections">{service && <input type="hidden" name="id" value={service.id}/>}<section className="admin-form-section"><header className="admin-form-section__heading"><h2>General</h2><p>Service identity and public listing copy.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="service-title">Title</label><input id="service-title" name="title" defaultValue={service?.title} required minLength={2} maxLength={140}/></div><div className="admin-field"><label htmlFor="service-slug">URL slug</label><input id="service-slug" name="slug" defaultValue={service?.slug} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></div><div className="admin-field"><label htmlFor="service-number">Display number</label><input id="service-number" name="number" defaultValue={service?.number || "01"} required maxLength={8}/></div><div className="admin-field"><label htmlFor="service-order">Sort order</label><input id="service-order" name="sortOrder" type="number" defaultValue={service?.sort_order || 0}/></div><div className="admin-field admin-field--wide"><label htmlFor="service-summary">Short summary</label><textarea id="service-summary" name="summary" defaultValue={service?.summary} required minLength={20} maxLength={400}/></div><div className="admin-field admin-field--wide"><label htmlFor="service-description">Full description</label><textarea id="service-description" name="description" defaultValue={service?.description}/></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>Capabilities & projects</h2><p>Structured lists keep the service page concise and scannable.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="service-capabilities">Capabilities</label><textarea id="service-capabilities" name="capabilities" defaultValue={service?.capabilities?.join("\n")}/><small>One capability per line.</small></div><div className="admin-field"><label htmlFor="service-projects">Related project slugs</label><textarea id="service-projects" name="relatedProjects" defaultValue={service?.related_project_slugs?.join("\n")}/><small>One project slug per line.</small></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>Media & icon</h2><p>Upload to Supabase Storage or select approved imagery.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field--wide"><MediaPicker name="serviceImage" label="Service image" value={image} assets={assets} requiredAlt/></div><div className="admin-field"><label htmlFor="service-icon">Optional icon name</label><input id="service-icon" name="icon" defaultValue={service?.icon||""} maxLength={80} placeholder="building"/><small>Uses the approved application icon set only.</small></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>SEO</h2><p>Optional overrides; title and summary are used by default.</p></header><div className="admin-form-section__body admin-form-grid"><div className="admin-field"><label htmlFor="service-seo-title">SEO title</label><input id="service-seo-title" name="seoTitle" defaultValue={service?.seo_title || ""} maxLength={70}/></div><div className="admin-field"><label htmlFor="service-canonical">Canonical URL</label><input id="service-canonical" name="canonicalUrl" defaultValue={service?.canonical_url||""} placeholder="/services/service-slug"/></div><div className="admin-field admin-field--wide"><label htmlFor="service-seo-description">SEO description</label><textarea id="service-seo-description" name="seoDescription" defaultValue={service?.seo_description || ""} maxLength={180}/></div><div className="admin-field--wide"><MediaPicker name="serviceOg" label="Open Graph image" value={og} assets={assets}/></div></div></section>
    <section className="admin-form-section"><header className="admin-form-section__heading"><h2>Publishing</h2><p>Disabled services are removed from public navigation and pages.</p></header><div className="admin-form-section__body admin-form-grid"><label className="admin-field"><span>Visibility</span><span><input name="active" type="checkbox" defaultChecked={service?.active ?? true}/> Active on website</span></label><label className="admin-field"><span>Featured placement</span><span><input name="featured" type="checkbox" defaultChecked={service?.featured}/> Feature this service</span></label></div></section><footer className="admin-form-footer"><Link className="admin-button" href="/admin/services">Cancel</Link><button className="admin-button admin-button--primary" type="submit">{service ? "Save changes" : "Create service"}</button></footer></form>;
}
