import { saveSetting } from "@/app/admin/(protected)/actions";
import { AdminPageHeader, EmptyState, formatDate } from "@/components/admin/ui";
import { getSiteSettings } from "@/lib/admin/data";

export const metadata={title:"Settings"};
export default async function SettingsPage(){const settings=await getSiteSettings();const configured=Boolean(process.env.SUPABASE_URL&&process.env.SUPABASE_SECRET_KEY);return <main className="admin-page"><AdminPageHeader eyebrow="System / Configuration" title="Settings" description="Business information, SEO defaults, social links, and safe integration status."/>
  <div className="admin-two-column"><section className="admin-panel"><header className="admin-panel__header"><h2>Integrations</h2></header><div className="admin-panel__body admin-code-status"><div><span>Supabase</span><span>{configured?"Connected":"Not configured"}</span></div><div><span>Email delivery</span><span>Database-only</span></div><div><span>Admin media</span><span>Supabase Storage</span></div><div><span>Cloudflare runtime</span><span>OpenNext ready</span></div></div></section><section className="admin-panel"><header className="admin-panel__header"><h2>Security</h2></header><div className="admin-panel__body"><p style={{margin:0,color:"var(--admin-muted)",fontSize:".72rem",lineHeight:1.7}}>Secret values are never shown here. Admin access requires a valid Supabase Auth session and an active approved profile. Database and Storage writes are protected by RLS.</p></div></section></div>
  <div className="admin-form-sections" style={{marginTop:"1rem"}}>{settings.length?settings.map((item)=><form action={saveSetting} className="admin-form-section" key={item.key}><input type="hidden" name="key" value={item.key}/><input type="hidden" name="label" value={item.label}/><header className="admin-form-section__heading"><h2>{item.label}</h2><p>Last updated {formatDate(item.updated_at)}</p></header><div className="admin-form-section__body"><div className="admin-field"><label htmlFor={`setting-${item.key}`}>Structured values</label><textarea id={`setting-${item.key}`} name="value" rows={7} defaultValue={JSON.stringify(item.value,null,2)} required/></div><label className="admin-field" style={{marginTop:".8rem"}}><span><input name="isPublic" type="checkbox" defaultChecked={item.is_public}/> Safe for public website reads</span></label></div><footer className="admin-form-footer"><button className="admin-button admin-button--primary">Save {item.label}</button></footer></form>):<section className="admin-panel"><EmptyState title="No settings found" copy="Run the admin CMS migration to create safe settings groups."/></section>}</div>
  </main>}
